from datetime import datetime
import ibm_db as db
import tweepy
import csv


class Watcher(tweepy.StreamListener):
    """
    Collects tweets from a Twitter stream and records them.

    API - an authorised Tweepy API object
    filter_list - a list of search strings
    connection - an ibm_db connection object
    out - a name for the outfile/table
    out_type - a string describing where the results should be sent: 'file', 'db', or 'both'
    """
    def __init__(self, api, filter_list, connection=None, out=None, out_type="file"):

        self.api = api
        self.connection = connection
        self.out = out
        self.out_type = out_type
        self.filter = filter_list if type(filter_list) == list else [filter_list]

        # Set up the outfile and/or database
        if self.out_type == "file" or self.out_type == "both":
            self.set_up_file()
        if self.connection and (self.out_type == "db" or self.out_type == "both"):
            self.set_up_db_table()

        # Raise an error if credentials are invalid
        if not self.api.verify_credentials():
            self.on_error("Invalid credentials.")        

    def prepare_status(self, status):
        """
        Extracts the desired data from a status.
        """
        text = status.extended_tweet["full_text"] \
        if hasattr(status, "extended_tweet") else status.text

        text.encode("utf-8")

        data = [text,
                status.author.screen_name,
                status.created_at,
                status.author.verified,
                status.source
                ]

        return data

    def set_up_file(self):
        """
        Create and format the outfile.
        """
        out_file = self.out + ".csv"
        with open(out_file, "a") as file:
            writer = csv.writer(file)
            writer.writerow(["text", "author",
                             "created_at",
                             "verified",
                             "source"])

    def set_up_db_table(self):
        """
        Create the database table.
        """
        
        # Check if the table exists.
        sql = f"SELECT name FROM SYSIBM.SYSTABLES WHERE type = 'T' AND name = '{self.out.upper()}';"
        tweets_table = db.fetch_tuple(db.exec_immediate(self.connection, sql))

        # If the table doesn't exist, create it.
        if not tweets_table:
            sql = f"""CREATE TABLE {self.out.upper()} (
                tweet_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                text VARCHAR(350) NOT NULL,
                author VARCHAR(150) NOT NULL,
                created_at TIMESTAMP NOT NULL,
                verified BOOLEAN NOT NULL,
                source VARCHAR(150) NOT NULL
                );"""
            db.exec_immediate(self.connection, sql)

    def write_to_db(self, data):
        """
        Stores a prepared status on the cloud.
        """

        # Create the statement
        sql = f"""INSERT INTO {self.out.upper()} (text, author, created_at,
                  verified, source) VALUES ({"?, " * len(data)}"""[:-2] + ");"

        # Add the relevant values to the statement
        stmt = db.prepare(self.connection, sql)

        # Loop through the data, binding each to the statement
        for x in range(1, len(data) + 1):
            db.bind_param(stmt, x, data[x - 1])
        
        # Actually write to the database
        result = db.execute(stmt)

    def write_to_file(self, data):
        """
        Writes a prepared status to a .csv.
        """
        with open(self.out + ".csv", "a", encoding="utf8") as file:
            writer = csv.writer(file, delimiter="\t")
            writer.writerow(data)

    def on_status(self, status):
        """
        When a tweet comes down the stream, send it in the right direction.
        """
        data = self.prepare_status(status)
        if self.out_type == "file" or self.out_type == "both":
            self.write_to_file(data)
        if self.connection and (self.out_type == "db" or self.out_type == "db"):
            self.write_to_db(data)

    def on_error(self, error):
        """
        If Twitter returns an error, log it.
        """
        print(datetime.now(), "Error:", error)
